use_frameworks!

platform :ios, '8.0'

target 'CWFoundation_Example' do
  pod 'CWFoundation', :path => '../'

  target 'CWFoundation_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
